In [1]:
# 11주차 과제

In [4]:
# How to import NumPy
import numpy as np

In [5]:
# Reading the example code
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [6]:
# What’s the difference between a Python list and a NumPy array?

In [7]:
# What is an array?
a = np.array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
print(a[0])

[1 2 3 4]


In [11]:
# More information about arrays
[[0., 0., 0.], [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [14]:
# How to create a basic array
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [13]:
np.zeros(2)

array([0., 0.])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [19]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [21]:
# Adding, removing, and sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# How do you know the shape and size of an array?
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [31]:
# Can you reshape an array?
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [32]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [34]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [40]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [41]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [43]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [44]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [49]:
# Indexing and slicing
data = np.array([1, 2, 3])
data[1]

2

In [50]:
data[0:2]

array([1, 2])

In [51]:
data[1:]

array([2, 3])

In [52]:
data[-2:]

array([2, 3])

In [54]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [55]:
five_up = (a >= 5)
print(a[five_up])

In [56]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [57]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [58]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [61]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [62]:
print(a[b])

[1 2 3 4]


In [63]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [64]:
# How to create an array from existing data

In [65]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [67]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [68]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [69]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [73]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [74]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
b2 = a.copy()

In [76]:
# Basic array operations
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [79]:
data - ones

array([0, 1])

In [80]:
data * data

array([1, 4])

In [81]:
data / data

array([1., 1.])

In [82]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [84]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [85]:
b.sum(axis=1)

array([2, 4])

In [86]:
# Broadcasting

In [87]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [88]:
# More useful array operations

In [89]:
data.max()

2.0

In [90]:
data.min()

1.0

In [91]:
data.sum()

3.0

In [93]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()

4.8595784

In [94]:
a.min()

0.05093587

In [95]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [97]:
# Creating matrices
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
data[0, 1]

2

In [99]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [100]:
data[0:2, 0]

array([1, 3])

In [101]:
data.max()

6

In [102]:
data.min()

1

In [103]:
data.sum()

21

In [104]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [105]:
data.max(axis=0)

array([5, 6])

In [106]:
data.max(axis=1)

array([2, 5, 6])

In [107]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [109]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [110]:
np.ones(3)

array([1., 1., 1.])

In [111]:
np.zeros(3)

array([0., 0., 0.])

In [112]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.02734279, 0.52473246, 0.37401328])

In [113]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [114]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [115]:
rng.random((3, 2)) 

array([[0.9184014 , 0.31217812],
       [0.59777029, 0.91333098],
       [0.53171234, 0.13894125]])

In [116]:
# Generating random numbers
rng.integers(5, size=(2, 4)) 

array([[3, 4, 0, 2],
       [0, 2, 1, 4]], dtype=int64)

In [119]:
# How to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [120]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [121]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [122]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [123]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [125]:
# Transposing and reshaping a matrix

In [126]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [128]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [130]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [131]:
# How to reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [132]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [133]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [134]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [135]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [ ]:
# Reshaping and flattening multidimensional arrays

In [137]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [138]:
a1 = x.flatten()
a1[0] = 99
print(x) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
a2 = x.ravel()
a2[0] = 98
print(x) 

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
